# Generated by Django 5.0.4 on 2024-04-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_reviews_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
